server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ksypobheonqsfr:520766edecdf2fdd21edeb2a6edbc1a39afa642a3a0c9269841c43f6e9e6449a@ec2-34-230-115-172.compute-1.amazonaws.com:5432/d3bthd0v2tkif1

    username: ksypobheonqsfr
    password: 520766edecdf2fdd21edeb2a6edbc1a39afa642a3a0c9269841c43f6e9e6449a
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Santander Dev Week - DIO
